import { jsPDF } from "jspdf";
import { REPORT_SECTIONS } from "./reports-data";

export type ReportDocInput = {
  name: string;
  typeLabel: string;
  description: string;
  bodyText?: string;
  operation: string;
  period: string;
  generatedBy: string;
  generatedAt: string;
  format: "PDF" | "CSV";
  layout: "Standard" | "Compact";
  language: string;
  detailLevel: string;
  includeMap: boolean;
  showLayers: boolean;
  sectionIds: string[];
  sectionNotes?: Record<string, string>;
  metricValues?: Record<string, string>;
  mapNote?: string;
};

export type ReportMetric = { label: string; value: string };
export type ReportTableRow = { section: string; item: string; detail: string };

const DEFAULT_METRICS: ReportMetric[] = [
  { label: "Groups", value: "3" },
  { label: "Personnel", value: "24" },
  { label: "Alerts", value: "12" },
  { label: "Geofences", value: "4" },
  { label: "Tickets", value: "5" },
  { label: "Devices", value: "18" },
];

export function reportMetrics(values?: Record<string, string>): ReportMetric[] {
  return DEFAULT_METRICS.map((item) => ({
    label: item.label,
    value: values?.[item.label] ?? item.value,
  }));
}

export function selectedSections(sectionIds: string[], notes?: Record<string, string>) {
  return REPORT_SECTIONS.filter((item) => sectionIds.includes(item.id)).map((item) => ({
    ...item,
    hint: notes?.[item.id]?.trim() || item.hint,
  }));
}

export function reportTableRows(input: ReportDocInput): ReportTableRow[] {
  const sections = selectedSections(input.sectionIds, input.sectionNotes);
  const base: ReportTableRow[] = [
    { section: "Meta", item: "Report Name", detail: input.name },
    { section: "Meta", item: "Type", detail: input.typeLabel },
    { section: "Meta", item: "Operation", detail: input.operation },
    { section: "Meta", item: "Period", detail: input.period },
    { section: "Meta", item: "Generated By", detail: input.generatedBy },
    { section: "Meta", item: "Generated At", detail: input.generatedAt },
    { section: "Meta", item: "Language", detail: input.language },
    { section: "Meta", item: "Detail Level", detail: input.detailLevel },
  ];
  if (input.bodyText?.trim()) {
    base.push({ section: "Narrative", item: "Body", detail: input.bodyText.trim() });
  }
  for (const metric of reportMetrics(input.metricValues)) {
    base.push({ section: "Summary", item: metric.label, detail: metric.value });
  }
  for (const section of sections) {
    base.push({ section: "Content", item: section.label, detail: section.hint });
  }
  if (input.includeMap) {
    base.push({
      section: "Map",
      item: "Visualization",
      detail:
        input.mapNote?.trim()
        || (input.showLayers ? "Groups, personnel, geofences" : "Base map only"),
    });
  }
  return base;
}

function safeFilename(name: string, ext: string) {
  const base = name.trim().replace(/[^\w\-]+/g, "_").replace(/_+/g, "_").slice(0, 80) || "report";
  return `${base}.${ext}`;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function buildCsv(input: ReportDocInput) {
  const rows = reportTableRows(input);
  const lines = [
    ["Section", "Item", "Detail"].join(","),
    ...rows.map((row) =>
      [row.section, row.item, row.detail]
        .map((cell) => `"${String(cell).replace(/"/g, '""')}"`)
        .join(","),
    ),
  ];
  return lines.join("\r\n");
}

export function downloadCsv(input: ReportDocInput) {
  const csv = buildCsv(input);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  triggerDownload(blob, safeFilename(input.name, "csv"));
  return { sizeLabel: `${Math.max(1, Math.round(blob.size / 1024))} KB` };
}

export function downloadPdf(input: ReportDocInput) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = input.layout === "Compact" ? 36 : 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  function ensureSpace(needed: number) {
    if (y + needed <= pageHeight - margin) return;
    doc.addPage();
    y = margin;
  }

  function writeWrapped(text: string, size: number, weight: "normal" | "bold" = "normal", color = "#0f172a") {
    doc.setFont("helvetica", weight);
    doc.setFontSize(size);
    doc.setTextColor(color);
    const lines = doc.splitTextToSize(text, contentWidth) as string[];
    const lineHeight = size + 4;
    ensureSpace(lines.length * lineHeight);
    doc.text(lines, margin, y);
    y += lines.length * lineHeight;
  }

  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageWidth, 72, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("TRAXON TACTICAL OPS", margin, 28);
  doc.setFontSize(18);
  doc.text(input.name, margin, 52);
  y = 96;

  writeWrapped(input.description || "Operational report document.", 11, "normal", "#475569");
  y += 8;
  if (input.bodyText?.trim()) {
    writeWrapped(input.bodyText.trim(), 11, "normal", "#334155");
    y += 8;
  }

  const meta = [
    ["Type", input.typeLabel],
    ["Operation", input.operation],
    ["Period", input.period],
    ["Generated By", input.generatedBy],
    ["Generated At", input.generatedAt],
    ["Language", input.language],
    ["Detail", input.detailLevel],
    ["Layout", input.layout],
  ];
  for (const [label, value] of meta) {
    ensureSpace(18);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor("#64748b");
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor("#0f172a");
    doc.text(value, margin + 96, y);
    y += 16;
  }

  y += 10;
  writeWrapped("Key Metrics", 13, "bold");
  y += 4;
  for (const metric of reportMetrics(input.metricValues)) {
    ensureSpace(16);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor("#0f172a");
    doc.text(`${metric.label}`, margin, y);
    doc.setFont("helvetica", "bold");
    doc.text(metric.value, margin + 160, y);
    y += 16;
  }

  y += 10;
  writeWrapped("Included Sections", 13, "bold");
  y += 4;
  for (const section of selectedSections(input.sectionIds, input.sectionNotes)) {
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor("#0f172a");
    doc.text(`• ${section.label}`, margin, y);
    y += 14;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor("#475569");
    const lines = doc.splitTextToSize(section.hint, contentWidth - 12) as string[];
    doc.text(lines, margin + 12, y);
    y += lines.length * 13 + 6;
  }

  if (input.includeMap) {
    y += 6;
    writeWrapped("Map Visualization", 13, "bold");
    y += 4;
    ensureSpace(90);
    doc.setDrawColor(148, 163, 184);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, contentWidth, 80, 6, 6, "FD");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor("#64748b");
    const mapText =
      input.mapNote?.trim()
      || (input.showLayers
        ? "Map layer: groups, personnel, and geofences included."
        : "Map layer: base operational area only.");
    const mapLines = doc.splitTextToSize(mapText, contentWidth - 24) as string[];
    doc.text(mapLines, margin + 12, y + 36);
    y += 96;
  }

  ensureSpace(24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor("#94a3b8");
  doc.text("Generated by Traxon Reports · Confidential", margin, pageHeight - 24);

  const blob = doc.output("blob");
  triggerDownload(blob, safeFilename(input.name, "pdf"));
  return { sizeLabel: `${Math.max(1, Math.round(blob.size / 1024))} KB` };
}

export function downloadReport(input: ReportDocInput) {
  return input.format === "CSV" ? downloadCsv(input) : downloadPdf(input);
}

export function estimateSizeLabel(format: "PDF" | "CSV") {
  return format === "PDF" ? "~48 KB" : "~4 KB";
}
